var annotated_dup =
[
    [ "Game", "namespace_game.html", [
      [ "Logging", "namespace_game_1_1_logging.html", [
        [ "LogRouterConfig", "class_game_1_1_logging_1_1_log_router_config.html", "class_game_1_1_logging_1_1_log_router_config" ],
        [ "LogRouterHandler", "class_game_1_1_logging_1_1_log_router_handler.html", "class_game_1_1_logging_1_1_log_router_handler" ]
      ] ]
    ] ],
    [ "Billboard", "class_billboard.html", null ],
    [ "CameraOverlayFade", "class_camera_overlay_fade.html", null ],
    [ "CharacterCreator", "class_character_creator.html", "class_character_creator" ],
    [ "CharacterCreatorDebug", "class_character_creator_debug.html", null ],
    [ "CharacterFeaturePackSO", "class_character_feature_pack_s_o.html", "class_character_feature_pack_s_o" ],
    [ "CharacterModel", "class_character_model.html", "class_character_model" ],
    [ "CharacterVoicePackSO", "class_character_voice_pack_s_o.html", "class_character_voice_pack_s_o" ],
    [ "CoherencyBehaviour", "class_coherency_behaviour.html", "class_coherency_behaviour" ],
    [ "CoherencyVignette", "class_coherency_vignette.html", "class_coherency_vignette" ],
    [ "Contract", "class_contract.html", "class_contract" ],
    [ "ContractCardManager", "class_contract_card_manager.html", "class_contract_card_manager" ],
    [ "Crowd", "class_crowd.html", "class_crowd" ],
    [ "CrowdManager", "class_crowd_manager.html", "class_crowd_manager" ],
    [ "CrowdPoint", "class_crowd_point.html", "class_crowd_point" ],
    [ "CrowdPointAllocator", "class_crowd_point_allocator.html", "class_crowd_point_allocator" ],
    [ "CrowdSpawner", "class_crowd_spawner.html", "class_crowd_spawner" ],
    [ "DamageParticles", "class_damage_particles.html", null ],
    [ "DebugHurtboxDisplay", "class_debug_hurtbox_display.html", null ],
    [ "Elevator", "class_elevator.html", "class_elevator" ],
    [ "ElevatorOpener", "class_elevator_opener.html", null ],
    [ "EndGameMenu", "class_end_game_menu.html", "class_end_game_menu" ],
    [ "FloatingCard", "class_floating_card.html", "class_floating_card" ],
    [ "Follower", "class_follower.html", "class_follower" ],
    [ "GameplayTestTools", "class_gameplay_test_tools.html", null ],
    [ "GameState", "class_game_state.html", "class_game_state" ],
    [ "GuardFollower", "class_guard_follower.html", "class_guard_follower" ],
    [ "GuardLeader", "class_guard_leader.html", "class_guard_leader" ],
    [ "GuardTutorial", "class_guard_tutorial.html", "class_guard_tutorial" ],
    [ "Hitbox", "class_hitbox.html", "class_hitbox" ],
    [ "Hurtbox", "class_hurtbox.html", "class_hurtbox" ],
    [ "Init", "class_init.html", null ],
    [ "LazySusan", "class_lazy_susan.html", null ],
    [ "Leader", "class_leader.html", "class_leader" ],
    [ "LostGameDisplay", "class_lost_game_display.html", null ],
    [ "MainMenuManager", "class_main_menu_manager.html", "class_main_menu_manager" ],
    [ "NavMeshGenerator", "class_nav_mesh_generator.html", "class_nav_mesh_generator" ],
    [ "NPCDeathHandler", "class_n_p_c_death_handler.html", null ],
    [ "NPCEventManager", "class_n_p_c_event_manager.html", "class_n_p_c_event_manager" ],
    [ "NPCPather", "class_n_p_c_pather.html", "class_n_p_c_pather" ],
    [ "NPCSoundManager", "class_n_p_c_sound_manager.html", "class_n_p_c_sound_manager" ],
    [ "NPCSpawner", "class_n_p_c_spawner.html", "class_n_p_c_spawner" ],
    [ "Passerby", "class_passerby.html", "class_passerby" ],
    [ "PauseBlockerBehaviour", "class_pause_blocker_behaviour.html", null ],
    [ "PauseManager", "class_pause_manager.html", "class_pause_manager" ],
    [ "PauseMenuManager", "class_pause_menu_manager.html", "class_pause_menu_manager" ],
    [ "PlayerAttachedMenu", "class_player_attached_menu.html", null ],
    [ "PlayerDistanceSphere", "class_player_distance_sphere.html", "class_player_distance_sphere" ],
    [ "PlayerEnterTrigger", "class_player_enter_trigger.html", "class_player_enter_trigger" ],
    [ "SAPSArrowLights", "class_s_a_p_s_arrow_lights.html", null ],
    [ "SceneLoader", "class_scene_loader.html", "class_scene_loader" ],
    [ "ScoreDisplay", "class_score_display.html", null ],
    [ "Singleton< T >", "class_singleton-1-g.html", "class_singleton-1-g" ],
    [ "StartEndLevelPlatform", "class_start_end_level_platform.html", "class_start_end_level_platform" ],
    [ "Target", "class_target.html", "class_target" ],
    [ "TargetTutorial", "class_target_tutorial.html", null ],
    [ "TimeScaleManager", "class_time_scale_manager.html", null ],
    [ "TutorialLeave", "class_tutorial_leave.html", null ],
    [ "TutorialNPCRespawner", "class_tutorial_n_p_c_respawner.html", "class_tutorial_n_p_c_respawner" ],
    [ "TutorialPopup", "class_tutorial_popup.html", null ],
    [ "TutorialSpawner", "class_tutorial_spawner.html", "class_tutorial_spawner" ],
    [ "TutorialStateManager", "class_tutorial_state_manager.html", "class_tutorial_state_manager" ],
    [ "VisionBehaviour", "class_vision_behaviour.html", "class_vision_behaviour" ],
    [ "WeaponAligner", "class_weapon_aligner.html", null ],
    [ "WeaponManager", "class_weapon_manager.html", "class_weapon_manager" ],
    [ "WorldSpaceEventFeedback", "class_world_space_event_feedback.html", "class_world_space_event_feedback" ],
    [ "XRAlignmentProvider", "class_x_r_alignment_provider.html", null ],
    [ "XRPushbackProvider", "class_x_r_pushback_provider.html", "class_x_r_pushback_provider" ]
];